name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'util/*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8, 3.11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run pytest
        run: make test

  lint:
    name: Run format/linter/types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8, 3.11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Check Black formatting and flake8 rules
        run: make lint
      - name: Check types using MyPy
        run: make types
