name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'util/*'
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8, 3.11]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - uses: snok/install-poetry@v1
        with:
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Check Black formatting and flake8 rules
        run: poetry run make lint
      - name: Check types using MyPy
        run: |
          poetry run mypy --install-types --non-interactive
          poetry run make types
      - name: Run pytest
        run: poetry run make test
